### ISSUE TITLE
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown.

### ISSUE THREAD

**Issue by click2cloud-vivekg** [blueapple168/opengauss-docker#1]
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown.

**Comment by lasred** [comment]
Do you know what the cause of this issue is? I got the same error

**Comment by blueapple168** [comment]
> Do you know what the cause of this issue is? I got the same error

try it ...
RUN chmod 755 /usr/local/bin/entrypoint.sh

**Comment by blueapple168** [comment]
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "docker-entrypoint.sh": executable file not found in $PATH: unknown.

try it ...
RUN chmod 755 /usr/local/bin/entrypoint.sh
